### ISSUE TITLE
Pausar e Iniciar o Pomodor com Barra de Espaço

### ISSUE THREAD

**Issue by MrLeonardDude** [fopor/easyPomo#2]
Para comecar e parar o contador utilizando barra de espaço pode ser bem legal né. Dá para usar uns comandos marotos do JS. O que você acha @fopor

**Comment by fopor** [comment]
é uma boa ideia!, vamos fazer essa adição, por enquanto o comando de pause é só uma _flag_, acho que vai ser tranquilo de adicionar
